# Generated by Django 6.0.2 on 2026-03-02 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0003_add_repo_demo_highlight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-destaque', '-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
