<<<<<<< HEAD
# Generated by Django 6.0.2 on 2026-02-26 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(help_text="e.g., Bachelor's in Computer Science", max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if currently enrolled', null=True)),
                ('description', models.TextField(blank=True, help_text='GPA, achievements, relevant coursework, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_background', to='api_profile.profile')),
            ],
            options={
                'verbose_name': 'Academic Background',
                'verbose_name_plural': 'Academic Backgrounds',
                'ordering': ['-end_date', '-start_date'],
            },
        ),
    ]
=======
# Generated by Django 6.0.2 on 2026-02-26 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(help_text="e.g., Bachelor's in Computer Science", max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if currently enrolled', null=True)),
                ('description', models.TextField(blank=True, help_text='GPA, achievements, relevant coursework, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_background', to='api_profile.profile')),
            ],
            options={
                'verbose_name': 'Academic Background',
                'verbose_name_plural': 'Academic Backgrounds',
                'ordering': ['-end_date', '-start_date'],
            },
        ),
    ]
>>>>>>> origin/main
