# Generated by Django 6.0.2 on 2026-03-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicbackground',
            name='course',
            field=models.CharField(help_text="e.g., Bachelor's in Computer Science", max_length=50),
        ),
        migrations.AlterField(
            model_name='academicbackground',
            name='institution',
            field=models.CharField(max_length=80),
        ),
    ]
